apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: alpine-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: second-deployment
  minReplicas: 2 
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
